spring:
  application:
    name: vetpet
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: TDHHpnv5IJnRHus
    url: "jdbc:mysql://localhost:3306/vetpet_database?createDatabaseIfNotExist=true"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false